CREATE TABLE [dbo].[tblAddress]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Street] VARCHAR(255) NOT NULL, 
    [City] VARCHAR(255) NOT NULL, 
    [County] VARCHAR(255) NOT NULL, 
    [State] VARCHAR(2) NOT NULL, 
    [ZIP] VARCHAR(5) NOT NULL
)
