CREATE TABLE [dbo].[tblCustomer]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [MemberId] UNIQUEIDENTIFIER NOT NULL, 
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    [FirstName] VARCHAR(50) NOT NULL, 
    [LastName] VARCHAR(50) NOT NULL, 
    [AddressId] UNIQUEIDENTIFIER NOT NULL, 
    [Email] VARCHAR(50) NOT NULL
)
