CREATE TABLE [dbo].[tblHauntedLocation]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [AddressId] UNIQUEIDENTIFIER NOT NULL, 
    [Name] VARCHAR(100) NOT NULL, 
    [ImagePath] VARCHAR(250) NOT NULL
)
