CREATE TABLE [dbo].[tblHauntedEvent]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [HauntedLocationId] UNIQUEIDENTIFIER NOT NULL, 
    [ParticipantId] UNIQUEIDENTIFIER NOT NULL, 
    [Date] DATETIME NOT NULL, 
    [Description] VARCHAR(250) NOT NULL
)
