CREATE TABLE [dbo].[tblHauntedEvent]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [HauntedLocationId] UNIQUEIDENTIFIER NOT NULL,
    [Name] VARCHAR(255) NOT NULL, 
    [Date] DATETIME NOT NULL, 
    [Description] VARCHAR(255) NOT NULL, 
    [ImagePath] VARCHAR(255) NOT NULL
)
