CREATE TABLE [dbo].[tblMember]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [TierId] UNIQUEIDENTIFIER NOT NULL, 
    [NewsLetterId] UNIQUEIDENTIFIER NOT NULL, 
    [NewsLetterOpt] VARCHAR(50) NOT NULL, 
    [MemberOpt] VARCHAR(50) NOT NULL
)
