CREATE TABLE [dbo].[tblNewsLetter]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [HauntedEventId] UNIQUEIDENTIFIER NOT NULL, 
    [Description] VARCHAR(250) NOT NULL, 
    [Date] DATETIME NOT NULL
)
