CREATE TABLE [dbo].[tblOrder]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [CustomerId] UNIQUEIDENTIFIER NOT NULL, 
    [OrderDate] DATETIME NOT NULL, 
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [ShipDate] DATETIME NOT NULL
)
