CREATE TABLE [dbo].[tblOrder]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [InCartId] UNIQUEIDENTIFIER NOT NULL, 
    [CustomerId] UNIQUEIDENTIFIER NOT NULL, 
    [OrderDate] DATETIME NOT NULL, 
    [DeliverDate] DATETIME NOT NULL
)
