CREATE TABLE [dbo].[tblTour]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [HauntedLocationId] UNIQUEIDENTIFIER NOT NULL, 
    [TourName] VARCHAR(100) NOT NULL, 
    [Description] VARCHAR(50) NOT NULL
)
